name: Deploy React App to Cloud Run

on:
  push:
    branches:
      - Feature/DUOL-19/ci-cd-Dockerfile

env:
  REGION: europe-north1
  SERVICE_NAME: react-frontend
  REPO_NAME: react-app-repo
  IMAGE_NAME: react-app
  VERSION: v1.0.0

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest

    steps:
      # ✅ Étape 1 : Setup & SonarCloud Analysis
      - name: Setup & SonarCloud Analysis
        run: |
          echo "Setting up environment..."
          sudo apt-get update && sudo apt-get install -y yq
          echo "Running SonarCloud Scan..."
          sonar-scanner \
            -Dsonar.projectKey=YoussefHalleb_Duolingo \
            -Dsonar.organization=youssefhalleb \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # ✅ Étape 2 : Authenticate & Configure Docker
      - name: Authenticate & Configure Docker
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # ✅ Étape 3 : Build Docker Image
      - name: Build Docker Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          TAG="${{ env.VERSION }}-${SHORT_SHA}"
          IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${TAG}
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .

      # ✅ Étape 4 : Scan Docker Image with Trivy
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_URI }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      # ✅ Étape 5 : Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_URI }}

      # ✅ Étape 6 : Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          echo "Deploying new image to Cloud Run..."
          # Ici tu peux ajouter une commande gcloud run deploy si nécessaire

      # ✅ Étape 7 : Update ArgoCD Manifests
      - name: Update ArgoCD Manifests
        run: |
          git clone https://x-access-token:${{ secrets.MANIFESTS_TOKEN }}@github.com/YoussefHalleb/react-frontend-manifests.git
          cd react-frontend-manifests/base
          yq -i -y '.spec.template.spec.containers[0].image = "${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"' deployment.yaml
          git config user.email "ci-bot@github.com"
          git config user.name "CI Bot"
          git add deployment.yaml
          git commit -m "Update image to ${IMAGE_TAG}"
          git push
